import type { Language } from './types';

const messages = {
  en: {
    search: 'Search the web or your shortcuts', settings: 'Settings', add: 'Add shortcut', focus: 'Focus mode',
    appearance: 'Appearance', system: 'System', light: 'Light', dark: 'Dark', language: 'Language', auto: 'Auto',
    russian: 'Russian', english: 'English', searchEngine: 'Search engine', browserDefault: 'Browser default', clock24: '24-hour clock', seconds: 'Show seconds',
    compact: 'Compact shortcuts', layout: 'Shortcut layout', orbit: 'Orbit', smartTiles: 'Smart tiles', opened: 'Opened', automation: 'Automatic shortcuts', autoAddTopSites: 'Add frequently visited sites', autoAddTopSitesHint: 'Uses the browser’s complete top sites list. Radial sends nothing to its own servers.', permissionRequired: 'Browser permission was not granted', background: 'Background', backgroundHint: 'Stored only on this device for a faster, private start page.', backgroundDefault: 'Radial atmosphere', backgroundSelected: 'Custom image', backgroundPreview: 'Background preview', chooseImage: 'Choose image', removeBackground: 'Remove image', backgroundSaved: 'Background saved', backgroundRemoved: 'Background removed', backgroundError: 'Choose an image up to 5 MB', collections: 'Collections', collectionsHint: 'Group shortcuts into calm, focused spaces. Your existing links stay untouched when this is off.', enableCollections: 'Use collections', enableCollectionsFirst: 'Enable collections to import bookmarks', allLinks: 'All shortcuts', ungrouped: 'Unsorted', collectionEmpty: 'This collection is empty', addCollection: 'Add collection', collectionName: 'Collection name', collectionNamePlaceholder: 'For example, Work', collectionNameHint: 'Links stay safe if you rename or remove a collection.', collectionCreated: 'Collection created', collectionRenamed: 'Collection renamed', collectionDeleted: 'Collection deleted; links were kept', collectionDeleteConfirm: 'Delete this collection? Its links will stay in Radial, just become unsorted.', collectionExists: 'A collection with this name already exists', movedToCollection: 'Shortcut moved', renameCollection: 'Rename collection', deleteCollection: 'Delete collection', collectionSelect: 'Collection', noCollection: 'No collection', noCollections: 'No collections yet', bookmarkImport: 'Import browser bookmarks', bookmarkImportHint: 'Choose one folder. Its subfolders become collections and duplicate links are skipped.', importBookmarks: 'Choose bookmark folder', bookmarkImportTitle: 'Import bookmarks', bookmarkImportDescription: 'Select the folder to bring into Radial. Subfolders will become collections.', bookmarkFolder: 'Bookmark folder', bookmarksRoot: 'Bookmarks', bookmarkLinksFound: 'web links found', importSelected: 'Import selected folder', importing: 'Importing…', bookmarksNoFolders: 'No bookmark folders found', bookmarksPermission: 'Allow bookmark access to import a folder', bookmarksImportError: 'Could not read browser bookmarks', bookmarksNoLinks: 'This folder has no web links to import', bookmarksNoNewLinks: 'No new links found', bookmarksImported: 'Bookmarks imported', bookmarksSkipped: 'duplicates skipped',
    data: 'Your data', export: 'Export data', import: 'Import data', reset: 'Reset to defaults',
    close: 'Close', edit: 'Edit shortcut', remove: 'Remove', cancel: 'Cancel', save: 'Save', title: 'Name', url: 'Web address',
    titlePlaceholder: 'For example, GitHub', urlPlaceholder: 'https://example.com', invalidUrl: 'Enter a valid http(s) address',
    noResults: 'No matching shortcut. Press Enter to search the web.', searchFor: 'Search the web for', importError: 'Could not import this file',
    imported: 'Data imported', exported: 'Data exported', saved: 'Shortcut saved', deleted: 'Shortcut removed', resetDone: 'Defaults restored',
    reorderHint: 'Drag shortcuts to reorder', openSettings: 'Open settings', greetingMorning: 'Good morning', greetingDay: 'Good afternoon', greetingEvening: 'Good evening',
  },
  ru: {
    search: 'Поиск в интернете или по ссылкам', settings: 'Настройки', add: 'Добавить ссылку', focus: 'Режим фокуса',
    appearance: 'Оформление', system: 'Системная', light: 'Светлая', dark: 'Тёмная', language: 'Язык', auto: 'Авто',
    russian: 'Русский', english: 'English', searchEngine: 'Поисковая система', browserDefault: 'По умолчанию в браузере', clock24: '24-часовой формат', seconds: 'Показывать секунды',
    compact: 'Компактные ссылки', layout: 'Режим ссылок', orbit: 'Орбита', smartTiles: 'Умная плитка', opened: 'Открыто', automation: 'Автоматические ссылки', autoAddTopSites: 'Добавлять часто посещаемые сайты', autoAddTopSitesHint: 'Берёт весь конечный список популярных сайтов из браузера; Radial не отправляет его на свои серверы.', permissionRequired: 'Разрешение браузера не предоставлено', background: 'Фон', backgroundHint: 'Хранится только на этом устройстве для быстрой и приватной стартовой страницы.', backgroundDefault: 'Атмосфера Radial', backgroundSelected: 'Своё изображение', backgroundPreview: 'Предпросмотр фона', chooseImage: 'Выбрать изображение', removeBackground: 'Убрать изображение', backgroundSaved: 'Фон сохранён', backgroundRemoved: 'Фон убран', backgroundError: 'Выберите изображение до 5 МБ', collections: 'Коллекции', collectionsHint: 'Собирайте ссылки в спокойные рабочие пространства. При отключении существующие ссылки останутся на месте.', enableCollections: 'Использовать коллекции', enableCollectionsFirst: 'Сначала включите коллекции', allLinks: 'Все ссылки', ungrouped: 'Без коллекции', collectionEmpty: 'В этой коллекции пока нет ссылок', addCollection: 'Добавить коллекцию', collectionName: 'Название коллекции', collectionNamePlaceholder: 'Например, Работа', collectionNameHint: 'Ссылки сохранятся, даже если переименовать или удалить коллекцию.', collectionCreated: 'Коллекция создана', collectionRenamed: 'Коллекция переименована', collectionDeleted: 'Коллекция удалена, ссылки сохранены', collectionDeleteConfirm: 'Удалить эту коллекцию? Ссылки останутся в Radial, но станут без коллекции.', collectionExists: 'Коллекция с таким названием уже есть', movedToCollection: 'Ссылка перемещена', renameCollection: 'Переименовать коллекцию', deleteCollection: 'Удалить коллекцию', collectionSelect: 'Коллекция', noCollection: 'Без коллекции', noCollections: 'Коллекций пока нет', bookmarkImport: 'Импорт закладок браузера', bookmarkImportHint: 'Выберите одну папку. Вложенные папки станут коллекциями, дубликаты ссылок будут пропущены.', importBookmarks: 'Выбрать папку закладок', bookmarkImportTitle: 'Импорт закладок', bookmarkImportDescription: 'Выберите папку для импорта в Radial. Вложенные папки станут коллекциями.', bookmarkFolder: 'Папка закладок', bookmarksRoot: 'Закладки', bookmarkLinksFound: 'веб-ссылок найдено', importSelected: 'Импортировать выбранную папку', importing: 'Импорт…', bookmarksNoFolders: 'Папки закладок не найдены', bookmarksPermission: 'Разрешите доступ к закладкам, чтобы выбрать папку', bookmarksImportError: 'Не удалось прочитать закладки браузера', bookmarksNoLinks: 'В этой папке нет веб-ссылок', bookmarksNoNewLinks: 'Новых ссылок не найдено', bookmarksImported: 'Закладки импортированы', bookmarksSkipped: 'дубликатов пропущено',
    data: 'Ваши данные', export: 'Экспортировать', import: 'Импортировать', reset: 'Сбросить настройки',
    close: 'Закрыть', edit: 'Изменить ссылку', remove: 'Удалить', cancel: 'Отмена', save: 'Сохранить', title: 'Название', url: 'Веб-адрес',
    titlePlaceholder: 'Например, GitHub', urlPlaceholder: 'https://example.com', invalidUrl: 'Введите корректный адрес http(s)',
    noResults: 'Подходящих ссылок нет. Нажмите Enter для поиска.', searchFor: 'Искать в интернете', importError: 'Не удалось импортировать файл',
    imported: 'Данные импортированы', exported: 'Данные экспортированы', saved: 'Ссылка сохранена', deleted: 'Ссылка удалена', resetDone: 'Настройки сброшены',
    reorderHint: 'Перетаскивайте ссылки, чтобы менять порядок', openSettings: 'Открыть настройки', greetingMorning: 'Доброе утро', greetingDay: 'Добрый день', greetingEvening: 'Добрый вечер',
  },
} as const;

export type MessageKey = keyof typeof messages.en;

export function resolveLanguage(language: Language): 'ru' | 'en' {
  if (language !== 'auto') return language;
  const candidate = globalThis.navigator?.language?.toLowerCase() ?? 'en';
  return candidate.startsWith('ru') ? 'ru' : 'en';
}

export function makeTranslator(language: Language) {
  const locale = resolveLanguage(language);
  return { locale, t: (key: MessageKey) => messages[locale][key] };
}
